version: '3'

services:
  mongo:
    container_name: database
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - ./dev-datastore:/data/db

  app:
    container_name: SimpleApp
    build:
      context: .
      args:
        configuration: development
    volumes:
      - ./:/myapp
      - /myapp/node_modules
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_URI=mongodb://mongo:27017/todoDB
      - JWT_SECRET="mysecret1234@zonix"
      - JWT_DURATION=1h
    depends_on:
      - mongo
